In [ ]:
import numpy as np 
import dgd
import datamol as dm
from dgd.analysis.rdkit_functions import *
from dgd.diffusion_model_discrete import DiscreteDenoisingDiffusion
from omegaconf import DictConfig, OmegaConf
%load_ext autoreload
%autoreload 2

Found rdkit, all good


In [20]:
config = "/home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/expts/outputs/2023-09-05/14-41-22/.hydra/config.yaml"
config = OmegaConf.load(config)
config["general"]["wandb"] = "disabled"
config

{'general': {'name': 'run_1000dsteps_128batch', 'wandb': 'offline', 'gpus': 1, 'entity': 'fntwin', 'project': 'SAFE_SPACE', 'resume': None, 'test_only': None, 'check_val_every_n_epochs': 5, 'sample_every_val': 4, 'val_check_interval': None, 'samples_to_generate': 512, 'samples_to_save': 20, 'chains_to_save': 1, 'log_every_steps': 50, 'number_chain_steps': 50, 'overfit': 0, 'progress_bar': True, 'final_model_samples_to_generate': 10000, 'final_model_samples_to_save': 30, 'final_model_chains_to_save': 20, 'evaluate_all_checkpoints': False}, 'model': {'type': 'discrete', 'transition': 'marginal', 'model': 'graph_tf', 'diffusion_steps': 1000, 'diffusion_noise_schedule': 'cosine', 'n_layers': 5, 'extra_features': 'cycles', 'hidden_mlp_dims': {'X': 256, 'E': 128, 'y': 128}, 'hidden_dims': {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}, 'lambda_train': [5, 0]}, 'train': {'n_epochs': 3000, 'batch_size': 256, 'lr': 0.0002, 'clip_grad': None, 'save_m

In [21]:
checkpoint = "/home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/expts/outputs/2023-09-05/14-41-22/checkpoints/run_1000dsteps_128batch/epoch=759.ckpt"
model=DiscreteDenoisingDiffusion.from_config(config, checkpoint)

Dataset /home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/datasets/../../data/frag/mol_frag_graphs_100000.pt.gz loaded from file
Dataset sizes: train 64000, val 16000, test 20000
Saving split indices to /home/cristian_valencediscovery_com/dev/FragDiffusion/notebooks
[Noise schedule: cosine] alpha_bar: tensor([9.9996e-01, 9.9991e-01, 9.9986e-01,  ..., 9.6956e-06, 2.4239e-06,
        2.4243e-10])
Marginal distribution of the classes: tensor([0.2283, 0.0823, 0.0596, 0.0391, 0.0321, 0.0351, 0.0261, 0.0286, 0.0280,
        0.0195, 0.0157, 0.0166, 0.0199, 0.0132, 0.0130, 0.0145, 0.0149, 0.0116,
        0.0141, 0.0127, 0.0095, 0.0092, 0.0110, 0.0073, 0.0066, 0.0066, 0.0068,
        0.0068, 0.0054, 0.0063, 0.0060, 0.0081, 0.0047, 0.0070, 0.0053, 0.0062,
        0.0056, 0.0057, 0.0047, 0.0045, 0.0054, 0.0063, 0.0049, 0.0032, 0.0052,
        0.0050, 0.0044, 0.0042, 0.0033, 0.0037, 0.0037, 0.0032, 0.0024, 0.0029,
        0.0030, 0.0030, 0.0029, 0.0033, 0.0034, 0.0018, 0.0019, 0.0023, 0.00

/home/cristian_valencediscovery_com/mambaforge/envs/fragdiff/lib/python3.11/site-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
/home/cristian_valencediscovery_com/mambaforge/envs/fragdiff/lib/python3.11/site-packages/pytorch_lightning/utilities/parsing.py:197: UserWarning: Attribute 'train_metrics' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['train_metrics'])`.
  rank_zero_warn(
/home/cristian_valencediscovery_com/mambaforge/envs/fragdiff/lib/python3.11/site-packages/pytorch_lightning/utilities/parsing.py:197: UserWarning: Attribute 'sampling_metrics' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['sampling_metrics'])`.
  rank_zero_warn(


In [ ]:
mols=model.random_sample(batch_id = 1, batch_size=5, sanitize=True, num_nodes=7, return_samples=True)
#dm.viz.to_image(mols, use_svg=False)

Example of generated X:  tensor([12,  0,  9,  1, 47,  4, 14])
Example of generated E:  tensor([[0, 1, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 2, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 3, 0, 2],
        [1, 0, 0, 3, 0, 0, 0],
        [0, 2, 0, 0, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 0]])
Example of generated X:  tensor([64, 51, 48, 17,  3,  2,  0])
Example of generated E:  tensor([[0, 0, 2, 0, 2, 3, 2],
        [0, 0, 0, 0, 0, 0, 3],
        [2, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [2, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 1, 0, 0, 0],
        [2, 3, 0, 0, 0, 0, 0]])
Example of generated X:  tensor([40,  2,  4,  1,  9, 76,  4])
Example of generated E:  tensor([[0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 3, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 3, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [1, 3, 0, 3, 0, 0, 3],
        [0, 0, 0, 0, 0, 3, 0]])


In [ ]:
mols

[[tensor([12,  0,  9,  1, 47,  4, 14]),
  tensor([[0, 1, 0, 0, 1, 0, 0],
          [1, 0, 0, 0, 0, 2, 0],
          [0, 0, 0, 1, 0, 0, 0],
          [0, 0, 1, 0, 3, 0, 2],
          [1, 0, 0, 3, 0, 0, 0],
          [0, 2, 0, 0, 0, 0, 0],
          [0, 0, 0, 2, 0, 0, 0]])],
 [tensor([64, 51, 48, 17,  3,  2,  0]),
  tensor([[0, 0, 2, 0, 2, 3, 2],
          [0, 0, 0, 0, 0, 0, 3],
          [2, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 1, 0],
          [2, 0, 0, 0, 0, 0, 0],
          [3, 0, 0, 1, 0, 0, 0],
          [2, 3, 0, 0, 0, 0, 0]])],
 [tensor([40,  2,  4,  1,  9, 76,  4]),
  tensor([[0, 0, 0, 0, 0, 1, 0],
          [0, 0, 0, 0, 0, 3, 0],
          [0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 1, 3, 0],
          [0, 0, 0, 1, 0, 0, 0],
          [1, 3, 0, 3, 0, 0, 3],
          [0, 0, 0, 0, 0, 3, 0]])],
 [tensor([ 0, 22,  9,  0,  9,  6,  1]),
  tensor([[0, 2, 0, 0, 0, 0, 0],
          [2, 0, 0, 3, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 1],
          [0, 3, 0, 0, 0, 1, 3],
      

In [ ]:
model.sampling_metrics(mols, model.name, model.current_epoch, val_counter=-1, test=False)

Found rdkit, all good
Restored variables from /home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/analysis/scscore/model.ckpt-10654.as_numpy.pickle
Validity over 5 molecules: 40.00%
Number of connected components of 5 molecules: min:1.00 mean:1.00 max:1.00
Relaxed validity over 5 molecules: 40.00%
Uniqueness over 2 valid molecules: 100.00%
Novelty over 2 unique valid molecules: 100.00%
{'samples/Validity': 0.4, 'samples/Relaxed Validity': 0.4, 'samples/Uniqueness': 1.0, 'samples/Novelty': 1.0, 'samples/LogP': 0.8018399999999998, 'samples/QED': 0.3521465389686161, 'samples/SA_Score': 1.2525998577872255, 'samples/SCScore': 0.0}


[09:23:58] Explicit valence for atom # 15 C, 5, is greater than permitted
[09:23:58] Explicit valence for atom # 9 C, 5, is greater than permitted
[09:23:58] Explicit valence for atom # 5 N, 6, is greater than permitted
[09:23:58] Explicit valence for atom # 15 C, 5, is greater than permitted
[09:23:58] Explicit valence for atom # 9 C, 5, is greater than permitted
[09:23:58] Explicit valence for atom # 5 N, 6, is greater than permitted
/home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/analysis/scscore/scscore.py:80: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  dtype=np.bool,


FileNotFoundError: [Errno 2] No such file or directory: 'graphs/run_1000dsteps_128batch/valid_unique_molecules_e0_b-1.txt'

In [14]:
mols

In [37]:

import pathlib
import hydra
import os, sys
import torch
sys.path.append('../')

import torch
import wandb
import hydra
import omegaconf
from omegaconf import DictConfig
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.utilities.warnings import PossibleUserWarning

from dgd import utils
from dgd.datasets.frag_dataset import FragDataset, FragDataModule, FragDatasetInfos
from dgd.analysis.frag_utils import PyGGraphToMolConverter, FragSamplingMetrics
from dgd.datasets.frag_dataset import FRAG_GRAPH_FILE, FRAG_INDEX_FILE, FRAG_EDGE_FILE

In [44]:
print(model.Xdim, model.Xdim_output)
print(model.Edim, model.Edim_output)
print(model.ydim, model.ydim_output)

103 100
4 4
6 0


In [91]:
model.on_fit_start()

RuntimeError: DiscreteDenoisingDiffusion is not attached to a `Trainer`.

In [97]:
def get_dataloader(config):
    from dgd.diffusion.extra_features import DummyExtraFeatures, ExtraFeatures
    datamodule = FragDataModule(config)
    dataset_infos=config["dataset"]
    dataset_infos = FragDatasetInfos(datamodule,dataset_infos)
    if config.model.type == 'discrete' and config.model.extra_features is not None:
        extra_features = ExtraFeatures(config.model.extra_features, dataset_info=dataset_infos)
    else:
        extra_features = DummyExtraFeatures()
    domain_features = DummyExtraFeatures()

    dataset_infos.compute_input_output_dims(datamodule=datamodule, extra_features=extra_features,
                                            domain_features=domain_features)
    return datamodule, dataset_infos

datamod, infos=get_dataloader(config)

Dataset /home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/datasets/../../data/frag/mol_frag_graphs_100000.pt.gz loaded from file
Dataset sizes: train 64000, val 16000, test 20000
Saving split indices to /home/cristian_valencediscovery_com/dev/FragDiffusion/notebooks


In [112]:
example_batch = next(iter(datamod.train_dataloader()))
ex_dense, node_mask = utils.to_dense(
            example_batch.x,
            example_batch.edge_index,
            example_batch.edge_attr,
            example_batch.batch,
        )
example_data = {
            "X_t": ex_dense.X,
            "E_t": ex_dense.E,
            "y_t": example_batch["y"],
            "node_mask": node_mask,
        }

In [128]:
infos.nodes_dist.sample_n(10, device="cpu")

tensor([ 7,  8,  7,  8,  6,  9,  7,  8, 10,  6])

In [143]:
from dgd import utils
frags=FragDataset("../data/frag/mol_frag_graphs_100000.pt.gz")

Dataset /home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/datasets/../../data/../data/frag/mol_frag_graphs_100000.pt.gz loaded from file


In [147]:
frags[0].x

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])

In [142]:
from dgd.datasets.abstract_dataset import AbstractDataModule
datamod.prepare_data()

Dataset /home/cristian_valencediscovery_com/dev/FragDiffusion/dgd/datasets/../../data/frag/mol_frag_graphs_100000.pt.gz loaded from file
Data(x=[11, 100], edge_index=[2, 20], edge_attr=[20, 4], y=[1, 0], idx=0, n_nodes=[1])
Dataset sizes: train 64000, val 16000, test 20000
Saving split indices to /home/cristian_valencediscovery_com/dev/FragDiffusion/notebooks


In [139]:
t.train_dataloader()

TypeError: 'NoneType' object is not subscriptable

In [133]:
for data in datamod.dataloaders["train"]:
    num_classes = data.x.shape[1]

print(num_classes)

100


In [87]:
data = next(iter(iter(datamod.train_dataloader())))
data

DataBatch(x=[1783, 100], edge_index=[2, 3054], edge_attr=[3054, 4], y=[256, 0], idx=[256], n_nodes=[256], batch=[1783], ptr=[257])

In [88]:
dense_data, node_mask = utils.to_dense(data.x, data.edge_index, data.edge_attr, data.batch)
dense_data = dense_data.mask(node_mask)
X, E = dense_data.X, dense_data.E
noisy_data = model.apply_noise(X, E, data.y, node_mask)
extra_data = model.compute_extra_data(noisy_data)

In [117]:
model.forward(noisy_data, extra_data, node_mask).X.

RuntimeError: The size of tensor a (15) must match the size of tensor b (12) at non-singleton dimension 1